name: seab1ird.letitgo
description: seab1ird

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4

environment:
  sdk: ">=2.1.0 <3.0.0"

module:
  androidX: true

dependencies:
  image: ^2.1.12
  shadow: ^0.1.5
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  assets_audio_player: ^1.4.0
  provider: ^4.0.4
  startapp: ^0.5.1
  firebase_admob: ^0.10.2
  shared_preferences: ^0.5.8
  shimmer: ^1.1.1
  google_fonts: ^1.1.0
  flutter_gifimage: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/background0.png
    - assets/images/background1.png
    - assets/images/background2.png
    - assets/images/background3.png
    - assets/images/background4.png
    - assets/images/background5.png
    - assets/images/background6.png
    - assets/images/background7.png
    - assets/images/background8.png
    - assets/images/background9.png
    - assets/images/splash_background.png

    - assets/images/petal0.png
    - assets/images/petal1.png
    - assets/images/petal2.png
    - assets/images/petal3.png
    - assets/images/heart0.png
    - assets/images/heart1.png
    - assets/images/heart2.png
    - assets/images/heart3.png
    - assets/images/flower0.png
    - assets/images/flower1.png
    - assets/images/flower2.png
    - assets/images/soap_bubble.png

    - assets/images/logo.png
    - assets/images/disabled_tile.png
    - assets/images/splash_logo.png

    - assets/images/tile0.png
    - assets/images/tile1.png
    - assets/images/tile2.png
    - assets/images/tile3.png
    - assets/images/tile4.png

    - assets/sounds/a.wav
    - assets/sounds/c.wav
    - assets/sounds/e.wav
    - assets/sounds/f.wav
    - assets/sounds/Cartoon.mp3