name: seab1ird.vncomedies
description: seab1ird.vncomedies
version: 1.1.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_admob: ^0.9.0+7
  toast: ^0.1.3
  app_review: ^1.0.0
  ytview: ">=1.0.0 <1.1.0"
  dio: 2.1.6  #latest version
  flare_flutter: 1.7.3
  flare_dart: 2.2.5

flutter:
  uses-material-design: true

  assets:
   - images/banner.png
   - images/bg.png

   - images/Star.flr
   - images/movie_icon.flr
   - images/play_movie.flr
   - images/app_icon.flr

