name: sbsinhtrac
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.19

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_admob: ^0.9.0+1
  toast: ^0.1.3
  app_review: ^1.0.0
  ytview: ">=1.0.0 <1.1.0"
  font_awesome_flutter: 8.5.0
  flare_flutter: 1.7.3
  flare_dart: 2.2.5
  # youtube_player_flutter: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/icon_title.png
   - images/bg.jpg
   - images/star.png
   - images/history.png
   - images/info.png
   - images/logo.png
   - images/exit.png
   - images/intro_icon.png
   - images/eagle.png
   - images/mountain.png
   - images/water.png
   - images/main_whorl.png
   - images/main_loop.png
   - images/main_arch.png

   - images/wt_draw.png
   - images/ws_draw.png
   - images/we_draw.png
   - images/wc_draw.png
   - images/wd_draw.png
   - images/wi_draw.png
   - images/wp_draw.png
   - images/wx_draw.png

   - images/rl_draw.png
   - images/ul_draw.png
   - images/fl_draw.png
   
   - images/ar_draw.png
   - images/as_draw.png
   - images/at_draw.png
   - images/au_draw.png
   - images/ae_draw.png

   - images/WT.png
   - images/WS.png
   - images/WE.png
   - images/WI.png
   - images/WD.png
   - images/WC.png
   - images/UWP.png
   - images/WX1.png
   - images/WX2.png
   
   - images/UL_left.png
   - images/UL_right.png
   - images/RL_left.png
   - images/RL_right.png

   - images/AR.png
   - images/AS.png
   - images/AT.png
   - images/AU.png
   - images/SinhTrac.flr
   - images/Star.flr

  #  - images/.png
  #  - images/.png
  #  - images/.png
  #  - images/.png
  #  - images/.png
  #  - images/.png
  #  - images/.png
  #  - images/.png
  #  - images/.png
  #  - images/.png
  #  - images/.png
  #  - images/.png
   
   
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
