name: seab1ird.showyourself
description: seab1ird

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4

environment:
  sdk: ">=2.1.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_admob: ^0.9.0+1
  video_player: 0.10.1+3
  chewie: ^0.9.7
  flare_flutter: 1.7.3
  flare_dart: 2.2.5
  app_review: ^1.0.0
  provider: ^4.0.4
  assets_audio_player: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/Animation_1.png
    - images/Animation_0.png
    - images/bg.png
    - images/CreatedObject7_10.png
    - images/CreatedObject7_100.png
    - images/CreatedObject7_101.png
    - images/CreatedObject7_102.png
    - images/CreatedObject7_103.png
    - images/CreatedObject7_106.png
    - images/CreatedObject7_105.png
    - images/CreatedObject7_107.png
    - images/CreatedObject7_104.png
    - images/CreatedObject7_11.png
    - images/CreatedObject7_109.png
    - images/CreatedObject7_108.png
    - images/CreatedObject7_111.png
    - images/CreatedObject7_112.png
    - images/CreatedObject7_110.png
    - images/CreatedObject7_113.png
    - images/CreatedObject7_118.png
    - images/CreatedObject7_12.png
    - images/CreatedObject7_119.png
    - images/CreatedObject7_114.png
    - images/CreatedObject7_120.png
    - images/CreatedObject7_121.png
    - images/CreatedObject7_122.png
    - images/CreatedObject7_123.png
    - images/CreatedObject7_126.png
    - images/CreatedObject7_127.png
    - images/CreatedObject7_129.png
    - images/CreatedObject7_128.png
    - images/CreatedObject7_130.png
    - images/CreatedObject7_132.png
    - images/CreatedObject7_131.png
    - images/CreatedObject7_133.png
    - images/CreatedObject7_134.png
    - images/CreatedObject7_13.png
    - images/CreatedObject7_135.png
    - images/CreatedObject7_137.png
    - images/CreatedObject7_138.png
    - images/CreatedObject7_136.png
    - images/CreatedObject7_139.png
    - images/CreatedObject7_140.png
    - images/CreatedObject7_141.png
    - images/CreatedObject7_14.png
    - images/CreatedObject7_142.png
    - images/CreatedObject7_143.png
    - images/CreatedObject7_146.png
    - images/CreatedObject7_145.png
    - images/CreatedObject7_147.png
    - images/CreatedObject7_149.png
    - images/CreatedObject7_144.png
    - images/CreatedObject7_148.png
    - images/CreatedObject7_150.png
    - images/CreatedObject7_151.png
    - images/CreatedObject7_152.png
    - images/CreatedObject7_153.png
    - images/CreatedObject7_155.png
    - images/CreatedObject7_156.png
    - images/CreatedObject7_15.png
    - images/CreatedObject7_157.png
    - images/CreatedObject7_158.png
    - images/CreatedObject7_159.png
    - images/CreatedObject7_16.png
    - images/CreatedObject7_160.png
    - images/CreatedObject7_154.png
    - images/CreatedObject7_163.png
    - images/CreatedObject7_161.png
    - images/CreatedObject7_162.png
    - images/CreatedObject7_165.png
    - images/CreatedObject7_166.png
    - images/CreatedObject7_164.png
    - images/CreatedObject7_169.png
    - images/CreatedObject7_168.png
    - images/CreatedObject7_167.png
    - images/CreatedObject7_17.png
    - images/CreatedObject7_172.png
    - images/CreatedObject7_171.png
    - images/CreatedObject7_173.png
    - images/CreatedObject7_175.png
    - images/CreatedObject7_170.png
    - images/CreatedObject7_177.png
    - images/CreatedObject7_176.png
    - images/CreatedObject7_174.png
    - images/CreatedObject7_18.png
    - images/CreatedObject7_178.png
    - images/CreatedObject7_180.png
    - images/CreatedObject7_181.png
    - images/CreatedObject7_182.png
    - images/CreatedObject7_184.png
    - images/CreatedObject7_183.png
    - images/CreatedObject7_179.png
    - images/CreatedObject7_19.png
    - images/CreatedObject7_186.png
    - images/CreatedObject7_185.png
    - images/CreatedObject7_190.png
    - images/CreatedObject7_191.png
    - images/CreatedObject7_187.png
    - images/CreatedObject7_192.png
    - images/CreatedObject7_193.png
    - images/CreatedObject7_196.png
    - images/CreatedObject7_195.png
    - images/CreatedObject7_198.png
    - images/CreatedObject7_197.png
    - images/CreatedObject7_194.png
    - images/CreatedObject7_20.png
    - images/CreatedObject7_199.png
    - images/CreatedObject7_200.png
    - images/CreatedObject7_202.png
    - images/CreatedObject7_203.png
    - images/CreatedObject7_205.png
    - images/CreatedObject7_201.png
    - images/CreatedObject7_204.png
    - images/CreatedObject7_208.png
    - images/CreatedObject7_207.png
    - images/CreatedObject7_21.png
    - images/CreatedObject7_206.png
    - images/CreatedObject7_209.png
    - images/CreatedObject7_212.png
    - images/CreatedObject7_211.png
    - images/CreatedObject7_213.png
    - images/CreatedObject7_214.png
    - images/CreatedObject7_210.png
    - images/CreatedObject7_217.png
    - images/CreatedObject7_216.png
    - images/CreatedObject7_215.png
    - images/CreatedObject7_22.png
    - images/CreatedObject7_218.png
    - images/CreatedObject7_220.png
    - images/CreatedObject7_221.png
    - images/CreatedObject7_223.png
    - images/CreatedObject7_222.png
    - images/CreatedObject7_224.png
    - images/CreatedObject7_219.png
    - images/CreatedObject7_225.png
    - images/CreatedObject7_226.png
    - images/CreatedObject7_227.png
    - images/CreatedObject7_229.png
    - images/CreatedObject7_23.png
    - images/CreatedObject7_228.png
    - images/CreatedObject7_232.png
    - images/CreatedObject7_230.png
    - images/CreatedObject7_231.png
    - images/CreatedObject7_233.png
    - images/CreatedObject7_235.png
    - images/CreatedObject7_234.png
    - images/CreatedObject7_238.png
    - images/CreatedObject7_237.png
    - images/CreatedObject7_236.png
    - images/CreatedObject7_239.png
    - images/CreatedObject7_240.png
    - images/CreatedObject7_241.png
    - images/CreatedObject7_242.png
    - images/CreatedObject7_244.png
    - images/CreatedObject7_24.png
    - images/CreatedObject7_243.png
    - images/CreatedObject7_245.png
    - images/CreatedObject7_247.png
    - images/CreatedObject7_246.png
    - images/CreatedObject7_25.png
    - images/CreatedObject7_249.png
    - images/CreatedObject7_251.png
    - images/CreatedObject7_252.png
    - images/CreatedObject7_253.png
    - images/CreatedObject7_254.png
    - images/CreatedObject7_248.png
    - images/CreatedObject7_250.png
    - images/CreatedObject7_256.png
    - images/CreatedObject7_255.png
    - images/CreatedObject7_258.png
    - images/CreatedObject7_257.png
    - images/CreatedObject7_26.png
    - images/CreatedObject7_259.png
    - images/CreatedObject7_261.png
    - images/CreatedObject7_262.png
    - images/CreatedObject7_263.png
    - images/CreatedObject7_27.png
    - images/CreatedObject7_266.png
    - images/CreatedObject7_28.png
    - images/CreatedObject7_29.png
    - images/CreatedObject7_30.png
    - images/CreatedObject7_260.png
    - images/CreatedObject7_34.png
    - images/CreatedObject7_31.png
    - images/CreatedObject7_36.png
    - images/CreatedObject7_33.png
    - images/CreatedObject7_32.png
    - images/CreatedObject7_35.png
    - images/CreatedObject7_37.png
    - images/CreatedObject7_39.png
    - images/CreatedObject7_38.png
    - images/CreatedObject7_40.png
    - images/CreatedObject7_41.png
    - images/CreatedObject7_43.png
    - images/CreatedObject7_45.png
    - images/CreatedObject7_42.png
    - images/CreatedObject7_44.png
    - images/CreatedObject7_48.png
    - images/CreatedObject7_50.png
    - images/CreatedObject7_49.png
    - images/CreatedObject7_5.png
    - images/CreatedObject7_51.png
    - images/CreatedObject7_46.png
    - images/CreatedObject7_52.png
    - images/CreatedObject7_53.png
    - images/CreatedObject7_54.png
    - images/CreatedObject7_55.png
    - images/CreatedObject7_56.png
    - images/CreatedObject7_58.png
    - images/CreatedObject7_59.png
    - images/CreatedObject7_6.png
    - images/CreatedObject7_47.png
    - images/CreatedObject7_57.png
    - images/CreatedObject7_61.png
    - images/CreatedObject7_60.png
    - images/CreatedObject7_63.png
    - images/CreatedObject7_62.png
    - images/CreatedObject7_64.png
    - images/CreatedObject7_65.png
    - images/CreatedObject7_67.png
    - images/CreatedObject7_68.png
    - images/CreatedObject7_66.png
    - images/CreatedObject7_7.png
    - images/CreatedObject7_69.png
    - images/CreatedObject7_70.png
    - images/CreatedObject7_71.png
    - images/CreatedObject7_74.png
    - images/CreatedObject7_72.png
    - images/CreatedObject7_76.png
    - images/CreatedObject7_73.png
    - images/CreatedObject7_75.png
    - images/CreatedObject7_77.png
    - images/CreatedObject7_79.png
    - images/CreatedObject7_8.png
    - images/CreatedObject7_80.png
    - images/CreatedObject7_78.png
    - images/CreatedObject7_81.png
    - images/CreatedObject7_82.png
    - images/CreatedObject7_83.png
    - images/CreatedObject7_85.png
    - images/CreatedObject7_84.png
    - images/CreatedObject7_88.png
    - images/CreatedObject7_86.png
    - images/CreatedObject7_87.png
    - images/CreatedObject7_9.png
    - images/CreatedObject7_90.png
    - images/CreatedObject7_89.png
    - images/CreatedObject7_92.png
    - images/CreatedObject7_91.png
    - images/CreatedObject7_95.png
    - images/CreatedObject7_94.png
    - images/CreatedObject7_97.png
    - images/CreatedObject7_98.png
    - images/CreatedObject7_99.png
    - images/CreatedObject7_93.png
    - images/CreatedObjectsStarting11.png
    - images/CreatedObjectsStarting15.png
    - images/CreatedObjectsStarting16.png
    - images/CreatedObjectsStarting19.png
    - images/bg2.png
    - images/GameObject_234.png
    - images/CreatedObjectsStarting13.png
    - images/GlitzSparks_4.png
    - images/CreatedObject7_96.png
    - images/CreatedObjectsStarting14.png
    - images/heart.png
    - images/GlitzSparks_3.png
    - images/LevelChoice_1.png
    - images/LevelChoice_2.png
    - images/lockMc_1.png
    - images/musicOn.png
    - images/musicOff.png
    - images/nextButton.png
    - images/nextButton_1.png
    - images/play.png
    - images/PlayButton.png
    - images/replayButton.png
    - images/lockMc_2.png
    - images/soundOn.png
    - images/soundOff.png
    - images/UiButtonTTS_17.png
    - images/UiButtonTTS_18.png
    - images/star.png
    - images/UiButtonTTS_19.png
    - images/UiButtonTTS_24.png
    - images/UiButtonTTS_22.png
    - images/UiButtonTTS_20.png
    - images/CreatedObjectsStarting10.png

    - images/changing_screen.flr
    - images/changing_item.flr
    - images/animated_screen2.flr
    - images/play_button.flr
    - images/previous_item_list.flr
    - images/next_item_list.flr

    - sounds/giggle.ogg
    - sounds/music1.ogg
    - sounds/poof.ogg
    - sounds/test.ogg