name: seab1ird.hkmovies
description: seab1ird.hkmovies

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_admob: ^0.9.0+7
  toast: ^0.1.3
  app_review: ^1.0.0
  # youtube_player_flutter: 6.1.1
  flare_flutter: 1.7.3
  flare_dart: 2.2.5
  dio: ^3.0.9
  webview_media: ^0.1.2

flutter:
  uses-material-design: true

  assets:
   - images/banner.png
   - images/bg.png

   - images/Star.flr
   - images/movie_icon.flr
   - images/play_movie.flr
   - images/app_icon.flr

