name: seab1ird.hkmovies
description: seab1ird.hkmovies

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_admob: ^0.9.0+7
  toast: ^0.1.3
  app_review: ^1.0.0
  flare_flutter: 1.7.3
  flare_dart: 2.2.5
  dio: ^3.0.9
  video_player: 0.10.1+3
  chewie: ^0.9.10
  shimmer: ^1.1.1

flutter:
  uses-material-design: true

  assets:
   - images/banner.png
   - images/bg.png

   - images/Star.flr
   - images/movie_icon.flr
   - images/play_movie.flr
   - images/app_icon.flr

