name: seab1ird.disctest
description: seab1ird

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.9

environment:
  sdk: ">=2.10.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  adcolony: ^2.0.6
  provider: ^4.0.4
  flame: ^0.28.0
  adsunity: ^1.0.3
  ml_algo: ^15.3.0
  firebase_ml_vision: ^0.9.9
  image_picker: ^0.6.7+14
  startapp: ^0.5.1
  ironsource: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/star.png
   - images/bg.png
   - images/info.png
   - images/logo.png
   - images/exit.png
   - images/home_icon.png
   - images/logo_head.png
   - images/banner.png

   - images/dominance.png
   - images/influence.png
   - images/steadiness.png
   - images/caution.png

   - images/star.flr
   - images/disc.flr
   - images/logo_head.flr
   - images/result.flr
